### PR TITLE
Update Cheetah.cfg

### PR DESCRIPTION
**Pull request by ghost**
New pull request

### CODE REVIEW

**Comment by JamesErvin-5** [comment]
Oops, seems as if I made the pull to the master branch instead of the dev.
Sorry about that.

**Comment by KnightofStJohn** [comment]
you didnt have to make a new pull request. if you changed the branch from where you made the original PR, then the PR should be automatically updated.

have you checked in game if your patch acts as intended?

**Comment by JamesErvin-5** [comment]
I won't get a chance to until friday unfortunately.
Perhaps we could ask someone to test it out in the meantime?

**Comment by KnightofStJohn** [comment]
friday is good. there's no rush.

**Pull request closed without merging**
